name: culinex
description: "Culinex mobile client."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  camera: ^0.11.2+1
  flutter:
    sdk: flutter
  http: ^1.5.0
  http_parser: ^4.1.2
  image_picker: ^1.2.0
  mime: ^2.0.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
