name: culinex
description: "Culinex mobile client."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  camera: ^0.12.0+1
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  http: ^1.5.0
  http_parser: ^4.1.2
  image_picker: ^1.2.0
  intl: ^0.20.2
  mime: ^2.0.0
  path: ^1.9.1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
